#!/bin/bash
# SessionStart hook: write instruction shard + probe Chrome connection
# set -euo pipefail  # removed: races with plugin autoUpdate cache swap
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(dirname "$HOOK_DIR")"
# The shard is a hook-generated REGULAR FILE, not a symlink (passe-mezigo):
# a symlink into the plugin root dangles on every version bump until the
# next session, and dangled permanently when the install root was ephemeral
# (the Cowork-sandbox incident, dead for a week). A copy can only go stale,
# and this rewrite refreshes it every session start — same pattern as mise.
if [ -f "$PLUGIN_ROOT/instructions.md" ]; then
    mkdir -p "$HOME/.claude/rules"
    RULES_FILE="$HOME/.claude/rules/passe.md"
    # Remove any leftover symlink first — writing through one would clobber
    # its target (e.g. a working-tree instructions.md), not replace the link.
    rm -f "$RULES_FILE"
    {
        echo "<!-- Generated by the passe plugin's session-start.sh —"
        echo "     rewritten from the plugin's instructions.md every session."
        echo "     Edit the source in spm1001/passe, not this copy. -->"
        echo ""
        cat "$PLUGIN_ROOT/instructions.md"
    } > "$RULES_FILE"
fi

# Probe Chrome connection (2s timeout, best-effort)
# Skip for subagents — they inherit parent's connection knowledge
CONN_STATUS=""
if [ -z "${CLAUDE_SUBAGENT:-}" ] && command -v passe &>/dev/null; then
    CONN_STATUS=$(timeout 2 passe status 2>/dev/null || true)
fi

# Surface connection state if probe returned results
if [ -n "$CONN_STATUS" ]; then
    if echo "$CONN_STATUS" | grep -q "reachable=True"; then
        CHROME_VER=$(echo "$CONN_STATUS" | grep chrome_version | sed 's/.*=//')
        TABS=$(echo "$CONN_STATUS" | grep tabs_open | sed 's/.*=//')
        DETAIL="Chrome connected: ${CHROME_VER}, ${TABS} tab(s)"
    else
        DETAIL="Chrome unreachable — run 'passe status' for diagnostics; check the backend unit is up, or 'passe login <url>' starts a visible local Chrome"
    fi
    cat <<EOF
{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "${DETAIL}"}}
EOF
fi

# Consume stdin (hook protocol)
cat > /dev/null
exit 0
